# NPM 包发布工作流示例
name: Publish NPM Package

on:
  # 手动触发
  workflow_dispatch:
    inputs:
      version:
        description: '版本类型或具体版本号'
        required: true
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'
        default: 'patch'
      dist_tag:
        description: '发布标签'
        required: false
        type: choice
        options:
          - 'latest'
          - 'beta'
          - 'alpha'
        default: 'latest'

  # Release 发布时触发
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: 安装依赖
        run: npm ci
        
      - name: 运行 Lint
        run: npm run lint
        
      - name: 运行测试
        run: npm test
        
      - name: 发布到 NPM
        uses: Arktomson/actions/npm-publish@v1
        with:
          version: ${{ github.event.inputs.version || 'patch' }}
          dist_tag: ${{ github.event.inputs.dist_tag || 'latest' }}
          token: ${{ secrets.NPM_TOKEN }}
          access: 'public'
          
      - name: 更新 Git 标签
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "chore: bump version to $(node -p require('./package.json').version)"
          git push